[server]
runOnSave = true
fileWatcherType = "auto"
port = 8501
address = "0.0.0.0"

[theme]
base="light"
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#303030"
font="sans serif"
