[server]
runOnSave = true
fileWatcherType = "auto"
port = 8501
address = "0.0.0.0"



[theme]
base="dark"  # options: "light" or "dark"
primaryColor="#00BFA6"
backgroundColor="#0E1117"
secondaryBackgroundColor="#1E2228"
textColor="#FAFAFA"
font="sans serif"


